glueup:
  users_list: "/api/v2/users"
  memberships_list: "/api/v2/memberships"
  events_list: "/api/v2/events"
circle:
  list_members: "/community_members"
  invite_member: "/community_members"
  update_member: "/community_members/{member_id}"
  add_member_to_space: "/space_members"
  remove_member_from_space: "/space_members"
  list_spaces: "/spaces"
  list_space_members: "/space_members"
