default_spaces:
- '2411092'
events:
  default_space_id: '2411092'
  field_overrides:
    host: GlueUp Events
    rsvp_disabled: false
    send_email_confirmation: true
    send_email_reminder: true
  sync_settings:
    create_new: true
    delete_removed: false
    future_only: true
    published_only: true
    sync_attendees: false
    update_existing: true
plans_to_spaces:
  basic:
  - REPLACE_WITH_SPACE_ID
  corporate gold:
  - REPLACE_WITH_CORPORATE_SPACE_ID
  corporate platinum:
  - REPLACE_WITH_CORPORATE_SPACE_ID
  corporate silver:
  - REPLACE_WITH_CORPORATE_SPACE_ID
  premium:
  - REPLACE_WITH_SPACE_ID
tags:
  active:
  - Active
  lapsed:
  - Lapsed
